include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint

custom_lint:
  rules:
    # Enable riverpod_lint rules
    - riverpod_final_provider
    - riverpod_missing_provider_scope
    - riverpod_avoid_ref_read