name: curemate
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # 🔹 Latest Firebase Dependencies
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.1
  firebase_database: ^10.5.3
  cloud_firestore: ^4.17.5
  # 🔹 Riverpod & State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.1.1
  freezed_annotation: ^3.0.0

  # 🔹 Utility Packages
  connectivity_plus: ^6.1.3
  image_picker: ^1.1.2
  flutter_svg: ^2.0.17
  icons_launcher: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  google_mlkit_face_detection: ^0.13.1
  image: ^4.5.4
  dropdown_button2: ^2.3.9
  location: ^6.0.2
  permission_handler: ^12.0.0+1
  http: ^1.3.0
  lottie: ^3.3.1
  url_launcher: ^6.3.1
  smooth_page_indicator: ^1.2.1
  cached_network_image: ^3.4.0
  animate_do: ^4.2.0
  intl: ^0.20.2
  flutter_cache_manager: ^3.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # 🔹 Code Generation & Linting
  riverpod_generator: ^2.4.3
  build_runner: ^2.4.7
  retrofit_generator: ^9.1.1
  json_serializable: ^6.8.0

#dev_dependencies:
#  flutter_test:
#    sdk: flutter
##
##   The "flutter_lints" package below contains a set of recommended lints to
##   encourage good coding practices. The lint set provided by the package is
##   activated in the `analysis_options.yaml` file located at the root of your
##   package. See that file for information about deactivating specific lint
##   rules and activating additional ones.
#  flutter_lints:
#  riverpod_generator:
#  build_runner:
#  custom_lint:
#  riverpod_lint:
#  freezed:
#  retrofit_generator:
#  json_serializable:

#dev_dependency_overrides:
#  flutter_lints: ^4.0.0
#  riverpod_generator: ^2.4.3
#  build_runner: ^2.4.12
#  custom_lint: ^0.6.5
#  riverpod_lint: ^2.3.13
#  freezed: ^2.5.7
#  retrofit_generator: ^9.1.1
#  json_serializable: ^6.8.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/signing_up.json
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 200
    - family: Bangers
      fonts:
        - asset: assets/fonts/Bangers-Regular.ttf
          weight: 200
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 200

icons_launcher:
  image_path: "assets/app_main_ic.jpg"
  platforms:
    android:
      enable: true
    ios:
      enable: true