name: curemate
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # 🔹 Latest Firebase Dependencies
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.1
  firebase_database: ^10.5.3
  freezed: ^2.0.0
  # 🔹 Riverpod & State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.1.1
  freezed_annotation: ^3.0.0

  # 🔹 Utility Packages
  connectivity_plus: ^6.1.3
  image_picker: ^1.1.2
  flutter_svg: ^2.0.17
  icons_launcher: ^3.0.1

  # Use specific versions of Isar
  isar: 3.0.5
  isar_flutter_libs: 3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # 🔹 Code Generation & Linting
  riverpod_generator: ^2.4.3
  build_runner: ^2.4.7
  retrofit_generator: ^9.1.1
  json_serializable: ^6.8.0
  isar_generator: 3.0.5


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 200
    - family: Bangers
      fonts:
        - asset: assets/fonts/Bangers-Regular.ttf
          weight: 200
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 200

icons_launcher:
  image_path: "assets/app_main_ic.jpg"
  platforms:
    android:
      enable: true
    ios:
      enable: true